// Ravenwolf Availability Script (Hybrid Version)

// Live Proxy Config
const ICAL_URL = 'https://calendar.google.com/calendar/ical/ilsi4rnri8qtqnn95rsitlbq4c@group.calendar.google.com/private-2702f2b45bcbfe0dbf0256bedac6f46a/basic.ics';
const PROXY_URL = `https://api.allorigins.win/raw?url=${encodeURIComponent(ICAL_URL)}`;

// Fallback Config
const FALLBACK_URL = 'data.json'; // This file is generated by the GitHub Action
const TIMEOUT_MS = 4000; // Wait 4 seconds for live data before falling back

// Helper: Format Date to YYYY-MM-DD
function toYYYYMMDD(date) {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, '0');
    const d = String(date.getDate()).padStart(2, '0');
    return `${y}-${m}-${d}`;
}

// 1. Try fetching live data via Proxy
function fetchLiveCalendarWithTimeout(timeout) {
    return new Promise((resolve, reject) => {
        const timeoutId = setTimeout(() => reject(new Error('Live proxy connection timed out')), timeout);

        fetch(PROXY_URL)
            .then(response => {
                clearTimeout(timeoutId);
                if (!response.ok) throw new Error('Proxy returned error');
                return response.text(); 
            })
            .then(icsText => {
                // Parse raw ICS data using ical.js
                const jcalData = ICAL.parse(icsText);
                const comp = new ICAL.Component(jcalData);
                const vevents = comp.getAllSubcomponents('vevent');
                
                const busyDates = new Set();
                vevents.forEach(vevent => {
                    const event = new ICAL.Event(vevent);
                    const startDate = event.startDate.toJSDate();
                    const endDate = event.endDate.toJSDate();

                    // Normalize to local midnight loop
                    let loopDate = new Date(startDate.getFullYear(), startDate.getMonth(), startDate.getDate());

                    while (loopDate < endDate) {
                        busyDates.add(toYYYYMMDD(loopDate));
                        loopDate.setDate(loopDate.getDate() + 1);
                    }
                });
                resolve(Array.from(busyDates)); 
            })
            .catch(error => {
                clearTimeout(timeoutId);
                reject(error);
            });
    });
}

// 2. Try fetching the local JSON file
function fetchFallback() {
    return fetch(FALLBACK_URL)
        .then(response => {
            if (!response.ok) throw new Error('Local data.json not found');
            return response.json(); 
        });
}

// Main Execution
async function loadCalendarData() {
    let busyDates = [];
    let source = '';

    try {
        // Race: Try live proxy first
        busyDates = await fetchLiveCalendarWithTimeout(TIMEOUT_MS);
        source = 'Live';
    } catch (liveError) {
        console.warn('Live proxy failed, switching to fallback.', liveError.message);
        
        try {
            // Fallback: Use local JSON
            busyDates = await fetchFallback();
            source = 'Nightly Backup';
        } catch (fallbackError) {
            console.error('Critical Error: Both sources failed.', fallbackError);
            document.getElementById('loading').innerHTML = '<p style="color: red;">Error loading calendar.</p>';
            return;
        }
    }

    generateAvailabilityList(busyDates, source);
}

// Render the list
function generateAvailabilityList(busyDatesArray, source) {
    const listElement = document.getElementById('availability-list');
    const loadingElement = document.getElementById('loading');
    const busyDates = new Set(busyDatesArray); 

    const today = new Date();
    const currentDate = new Date(today);
    currentDate.setDate(today.getDate() + (5 - today.getDay() + 7) % 7); // Next Friday

    const endYear = today.getFullYear() + 1;
    const finalDate = new Date(endYear, 11, 31);

    const dateOptions = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
    let currentMonth = -1;

    while (currentDate <= finalDate) {
        const dayOfWeek = currentDate.getDay();
        
        if (dayOfWeek === 5 || dayOfWeek === 6) {
            if (currentDate.getMonth() !== currentMonth) {
                currentMonth = currentDate.getMonth();
                const monthName = currentDate.toLocaleString('default', { month: 'long' });
                const monthHeader = document.createElement('li');
                monthHeader.innerHTML = `<h3>${monthName} ${currentDate.getFullYear()}</h3>`;
                monthHeader.style.backgroundColor = '#eee';
                monthHeader.style.textAlign = 'center';
                listElement.appendChild(monthHeader);
            }
            
            const dateString = toYYYYMMDD(currentDate);
            const li = document.createElement('li');
            li.textContent = currentDate.toLocaleString('en-GB', dateOptions);

            if (busyDates.has(dateString)) {
                li.classList.add('unavailable');
                li.textContent += ' - UNAVAILABLE';
            } else {
                li.classList.add('available');
                li.textContent += ' - AVAILABLE';
            }
            listElement.appendChild(li);
        }
        currentDate.setDate(currentDate.getDate() + 1);
    }
    
    loadingElement.style.display = 'none';
}

document.addEventListener('DOMContentLoaded', () => {
    loadCalendarData();
});
